CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "AspNetRoles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FullName" text,
    "ImagemPerfil" text,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "Categorias" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(100) NOT NULL,
    CONSTRAINT "PK_Categorias" PRIMARY KEY ("Id")
);

CREATE TABLE "Combustiveis" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Tipo" character varying(50) NOT NULL,
    CONSTRAINT "PK_Combustiveis" PRIMARY KEY ("Id")
);

CREATE TABLE "Extras" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Descricao" character varying(100) NOT NULL,
    "Tipo" character varying(50) NOT NULL,
    CONSTRAINT "PK_Extras" PRIMARY KEY ("Id")
);

CREATE TABLE "Marcas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(100) NOT NULL,
    CONSTRAINT "PK_Marcas" PRIMARY KEY ("Id")
);

CREATE TABLE "Moradas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CodigoPostal" character varying(20) NOT NULL,
    "Localidade" character varying(100) NOT NULL,
    "Rua" character varying(200) NOT NULL,
    CONSTRAINT "PK_Moradas" PRIMARY KEY ("Id")
);

CREATE TABLE "NotificationPreferences" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdentityUserId" text NOT NULL,
    "EmailNotifications" boolean NOT NULL,
    "NewListingsAlerts" boolean NOT NULL,
    "PriceDropAlerts" boolean NOT NULL,
    "Newsletter" boolean NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_NotificationPreferences" PRIMARY KEY ("Id")
);

CREATE TABLE "Tipos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(100) NOT NULL,
    CONSTRAINT "PK_Tipos" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" integer NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" integer NOT NULL,
    "RoleId" integer NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" integer NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Utilizador" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" character varying(60) NOT NULL,
    "Email" character varying(254) NOT NULL,
    "Nome" character varying(120) NOT NULL,
    "PasswordHash" character varying(255) NOT NULL,
    "Estado" character varying(30),
    "Tipo" character varying(50),
    "ImagemPerfil" character varying(500),
    "MoradaId" integer,
    "IdentityUserId" integer NOT NULL,
    "Discriminator" character varying(13) NOT NULL,
    "NivelAcesso" character varying(50),
    "Preferencias" character varying(500),
    "DadosFaturacao" character varying(200),
    "Nif" character varying(20),
    "Nib" character varying(21),
    CONSTRAINT "PK_Utilizador" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Utilizador_AspNetUsers_IdentityUserId" FOREIGN KEY ("IdentityUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Utilizador_Moradas_MoradaId" FOREIGN KEY ("MoradaId") REFERENCES "Moradas" ("Id")
);

CREATE TABLE "Modelos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(100) NOT NULL,
    "MarcaId" integer NOT NULL,
    "TipoId" integer NOT NULL,
    CONSTRAINT "PK_Modelos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Modelos_Marcas_MarcaId" FOREIGN KEY ("MarcaId") REFERENCES "Marcas" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Modelos_Tipos_TipoId" FOREIGN KEY ("TipoId") REFERENCES "Tipos" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Avaliacoes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VendedorId" integer NOT NULL,
    "CompradorId" integer NOT NULL,
    "Data" timestamp with time zone NOT NULL,
    "Nota" integer NOT NULL,
    "Comentario" character varying(500),
    CONSTRAINT "PK_Avaliacoes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Avaliacoes_Utilizador_CompradorId" FOREIGN KEY ("CompradorId") REFERENCES "Utilizador" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Avaliacoes_Utilizador_VendedorId" FOREIGN KEY ("VendedorId") REFERENCES "Utilizador" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Contactos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(100) NOT NULL,
    "VendedorId" integer NOT NULL,
    CONSTRAINT "PK_Contactos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Contactos_Utilizador_VendedorId" FOREIGN KEY ("VendedorId") REFERENCES "Utilizador" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ContactosCompradores" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(100) NOT NULL,
    "CompradorId" integer NOT NULL,
    CONSTRAINT "PK_ContactosCompradores" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ContactosCompradores_Utilizador_CompradorId" FOREIGN KEY ("CompradorId") REFERENCES "Utilizador" ("Id") ON DELETE CASCADE
);

CREATE TABLE "DisponibilidadesVendedor" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VendedorId" integer NOT NULL,
    "DiaSemana" integer NOT NULL,
    "HoraInicio" interval NOT NULL,
    "HoraFim" interval NOT NULL,
    "IntervaloMinutos" integer NOT NULL,
    "Ativo" boolean NOT NULL,
    "DataCriacao" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_DisponibilidadesVendedor" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DisponibilidadesVendedor_Utilizador_VendedorId" FOREIGN KEY ("VendedorId") REFERENCES "Utilizador" ("Id") ON DELETE CASCADE
);

CREATE TABLE "FiltrosFavoritos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CompradorId" integer NOT NULL,
    "Nome" character varying(100),
    "MarcaId" integer,
    "ModeloId" integer,
    "TipoId" integer,
    "CategoriaId" integer,
    "CombustivelId" integer,
    "PrecoMax" numeric(10,2),
    "AnoMin" integer,
    "AnoMax" integer,
    "KmMax" integer,
    "Caixa" character varying(50),
    "Localizacao" character varying(100),
    "Ativo" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastCheckedAt" timestamp with time zone,
    "MaxAnuncioIdNotificado" integer NOT NULL,
    CONSTRAINT "PK_FiltrosFavoritos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FiltrosFavoritos_Utilizador_CompradorId" FOREIGN KEY ("CompradorId") REFERENCES "Utilizador" ("Id") ON DELETE CASCADE
);

CREATE TABLE "MarcasFavoritas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CompradorId" integer NOT NULL,
    "MarcaId" integer NOT NULL,
    CONSTRAINT "PK_MarcasFavoritas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MarcasFavoritas_Marcas_MarcaId" FOREIGN KEY ("MarcaId") REFERENCES "Marcas" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MarcasFavoritas_Utilizador_CompradorId" FOREIGN KEY ("CompradorId") REFERENCES "Utilizador" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "PedidosVendedor" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CompradorId" integer NOT NULL,
    "Nif" character varying(9) NOT NULL,
    "DadosFaturacao" character varying(500),
    "Motivacao" character varying(1000) NOT NULL,
    "Estado" character varying(20) NOT NULL,
    "DataPedido" timestamp with time zone NOT NULL,
    "DataResposta" timestamp with time zone,
    "AdminRespondeuId" integer,
    "MotivoRejeicao" character varying(500),
    CONSTRAINT "PK_PedidosVendedor" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PedidosVendedor_Utilizador_CompradorId" FOREIGN KEY ("CompradorId") REFERENCES "Utilizador" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PesquisasPassadas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Data" timestamp with time zone NOT NULL,
    "Count" integer NOT NULL,
    "CompradorId" integer NOT NULL,
    "Parametros" character varying(500),
    "Descricao" character varying(200),
    CONSTRAINT "PK_PesquisasPassadas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PesquisasPassadas_Utilizador_CompradorId" FOREIGN KEY ("CompradorId") REFERENCES "Utilizador" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Anuncios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Preco" numeric(10,2) NOT NULL,
    "Ano" integer,
    "Cor" character varying(50),
    "Descricao" character varying(2000),
    "Quilometragem" integer,
    "Titulo" character varying(200) NOT NULL,
    "Caixa" character varying(50),
    "Localizacao" character varying(100),
    "Portas" integer,
    "Lugares" integer,
    "Potencia" integer,
    "Cilindrada" integer,
    "Valor_sinal" numeric(10,2) NOT NULL,
    n_visualizacoes integer NOT NULL,
    "Estado" character varying(20) NOT NULL,
    "Destacado" boolean NOT NULL,
    "DataDestaque" timestamp with time zone,
    "DestaqueAte" timestamp with time zone,
    "VendedorId" integer NOT NULL,
    "MarcaId" integer,
    "ModeloId" integer,
    "CategoriaId" integer,
    "CombustivelId" integer,
    "TipoId" integer,
    CONSTRAINT "PK_Anuncios" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Anuncios_Categorias_CategoriaId" FOREIGN KEY ("CategoriaId") REFERENCES "Categorias" ("Id"),
    CONSTRAINT "FK_Anuncios_Combustiveis_CombustivelId" FOREIGN KEY ("CombustivelId") REFERENCES "Combustiveis" ("Id"),
    CONSTRAINT "FK_Anuncios_Marcas_MarcaId" FOREIGN KEY ("MarcaId") REFERENCES "Marcas" ("Id"),
    CONSTRAINT "FK_Anuncios_Modelos_ModeloId" FOREIGN KEY ("ModeloId") REFERENCES "Modelos" ("Id"),
    CONSTRAINT "FK_Anuncios_Tipos_TipoId" FOREIGN KEY ("TipoId") REFERENCES "Tipos" ("Id"),
    CONSTRAINT "FK_Anuncios_Utilizador_VendedorId" FOREIGN KEY ("VendedorId") REFERENCES "Utilizador" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AnuncioExtras" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AnuncioId" integer NOT NULL,
    "ExtraId" integer NOT NULL,
    CONSTRAINT "PK_AnuncioExtras" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AnuncioExtras_Anuncios_AnuncioId" FOREIGN KEY ("AnuncioId") REFERENCES "Anuncios" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AnuncioExtras_Extras_ExtraId" FOREIGN KEY ("ExtraId") REFERENCES "Extras" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "AnunciosFavoritos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CompradorId" integer NOT NULL,
    "AnuncioId" integer NOT NULL,
    "Campo" character varying(100),
    CONSTRAINT "PK_AnunciosFavoritos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AnunciosFavoritos_Anuncios_AnuncioId" FOREIGN KEY ("AnuncioId") REFERENCES "Anuncios" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AnunciosFavoritos_Utilizador_CompradorId" FOREIGN KEY ("CompradorId") REFERENCES "Utilizador" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Compras" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AnuncioId" integer NOT NULL,
    "CompradorId" integer NOT NULL,
    "Data" timestamp with time zone NOT NULL,
    "EstadoPagamento" character varying(30),
    CONSTRAINT "PK_Compras" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Compras_Anuncios_AnuncioId" FOREIGN KEY ("AnuncioId") REFERENCES "Anuncios" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Compras_Utilizador_CompradorId" FOREIGN KEY ("CompradorId") REFERENCES "Utilizador" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Conversas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Tipo" character varying(50) NOT NULL,
    "VendedorId" integer NOT NULL,
    "CompradorId" integer NOT NULL,
    "AnuncioId" integer NOT NULL,
    "UltimaMensagemData" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Conversas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Conversas_Anuncios_AnuncioId" FOREIGN KEY ("AnuncioId") REFERENCES "Anuncios" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Conversas_Utilizador_CompradorId" FOREIGN KEY ("CompradorId") REFERENCES "Utilizador" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Conversas_Utilizador_VendedorId" FOREIGN KEY ("VendedorId") REFERENCES "Utilizador" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Denuncia" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Descricao" character varying(2000) NOT NULL,
    "Estado" character varying(30),
    "DataDeDenuncia" timestamp with time zone NOT NULL,
    "DataEncerramento" timestamp with time zone,
    "CompradorId" integer NOT NULL,
    "AdministradorId" integer,
    "TipoDenuncia" character varying(21) NOT NULL,
    "AnuncioId" integer,
    "VendedorId" integer,
    "UtilizadorAlvoId" integer,
    CONSTRAINT "PK_Denuncia" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Denuncia_Anuncios_AnuncioId" FOREIGN KEY ("AnuncioId") REFERENCES "Anuncios" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Denuncia_Utilizador_AdministradorId" FOREIGN KEY ("AdministradorId") REFERENCES "Utilizador" ("Id"),
    CONSTRAINT "FK_Denuncia_Utilizador_CompradorId" FOREIGN KEY ("CompradorId") REFERENCES "Utilizador" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Denuncia_Utilizador_UtilizadorAlvoId" FOREIGN KEY ("UtilizadorAlvoId") REFERENCES "Utilizador" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Denuncia_Utilizador_VendedorId" FOREIGN KEY ("VendedorId") REFERENCES "Utilizador" ("Id")
);

CREATE TABLE "HistoricoAcao" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Data" timestamp with time zone NOT NULL,
    "Motivo" character varying(500),
    "TipoAcao" character varying(100) NOT NULL,
    "AdministradorId" integer NOT NULL,
    "AnuncioId" integer,
    "UtilizadorId" integer,
    CONSTRAINT "PK_HistoricoAcao" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_HistoricoAcao_Anuncios_AnuncioId" FOREIGN KEY ("AnuncioId") REFERENCES "Anuncios" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_HistoricoAcao_Utilizador_AdministradorId" FOREIGN KEY ("AdministradorId") REFERENCES "Utilizador" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_HistoricoAcao_Utilizador_UtilizadorId" FOREIGN KEY ("UtilizadorId") REFERENCES "Utilizador" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Imagens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ImagemCaminho" character varying(500) NOT NULL,
    "AnuncioId" integer,
    CONSTRAINT "PK_Imagens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Imagens_Anuncios_AnuncioId" FOREIGN KEY ("AnuncioId") REFERENCES "Anuncios" ("Id")
);

CREATE TABLE "Reservas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Data" timestamp with time zone NOT NULL,
    "Estado" character varying(30),
    "DataExpiracao" timestamp with time zone,
    "CompradorId" integer NOT NULL,
    "AnuncioId" integer NOT NULL,
    CONSTRAINT "PK_Reservas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Reservas_Anuncios_AnuncioId" FOREIGN KEY ("AnuncioId") REFERENCES "Anuncios" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Reservas_Utilizador_CompradorId" FOREIGN KEY ("CompradorId") REFERENCES "Utilizador" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Notificacoes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Conteudo" character varying(500) NOT NULL,
    "Data" timestamp with time zone NOT NULL,
    "PesquisasPassadasId" integer,
    "FiltrosFavId" integer,
    "AnuncioFavId" integer,
    "MarcasFavId" integer,
    "CompradorId" integer NOT NULL,
    CONSTRAINT "PK_Notificacoes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Notificacoes_AnunciosFavoritos_AnuncioFavId" FOREIGN KEY ("AnuncioFavId") REFERENCES "AnunciosFavoritos" ("Id"),
    CONSTRAINT "FK_Notificacoes_FiltrosFavoritos_FiltrosFavId" FOREIGN KEY ("FiltrosFavId") REFERENCES "FiltrosFavoritos" ("Id"),
    CONSTRAINT "FK_Notificacoes_MarcasFavoritas_MarcasFavId" FOREIGN KEY ("MarcasFavId") REFERENCES "MarcasFavoritas" ("Id"),
    CONSTRAINT "FK_Notificacoes_PesquisasPassadas_PesquisasPassadasId" FOREIGN KEY ("PesquisasPassadasId") REFERENCES "PesquisasPassadas" ("Id"),
    CONSTRAINT "FK_Notificacoes_Utilizador_CompradorId" FOREIGN KEY ("CompradorId") REFERENCES "Utilizador" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Mensagens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Conteudo" character varying(2000) NOT NULL,
    "Estado" character varying(30),
    "DataEnvio" timestamp with time zone NOT NULL,
    "Lida" boolean NOT NULL,
    "RemetenteId" integer NOT NULL,
    "ConversaId" integer NOT NULL,
    CONSTRAINT "PK_Mensagens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Mensagens_AspNetUsers_RemetenteId" FOREIGN KEY ("RemetenteId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Mensagens_Conversas_ConversaId" FOREIGN KEY ("ConversaId") REFERENCES "Conversas" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Visitas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Data" timestamp with time zone NOT NULL,
    "Estado" character varying(30) NOT NULL,
    "Observacoes" character varying(500),
    "CompradorId" integer NOT NULL,
    "AnuncioId" integer NOT NULL,
    "VendedorId" integer NOT NULL,
    "ReservaId" integer,
    "DataCriacao" timestamp with time zone NOT NULL,
    "DataAtualizacao" timestamp with time zone,
    CONSTRAINT "PK_Visitas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Visitas_Anuncios_AnuncioId" FOREIGN KEY ("AnuncioId") REFERENCES "Anuncios" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Visitas_Reservas_ReservaId" FOREIGN KEY ("ReservaId") REFERENCES "Reservas" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Visitas_Utilizador_CompradorId" FOREIGN KEY ("CompradorId") REFERENCES "Utilizador" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Visitas_Utilizador_VendedorId" FOREIGN KEY ("VendedorId") REFERENCES "Utilizador" ("Id") ON DELETE RESTRICT
);

INSERT INTO "Tipos" ("Id", "Nome")
VALUES (1, 'Carro');
INSERT INTO "Tipos" ("Id", "Nome")
VALUES (2, 'Mota');

CREATE INDEX "IX_AnuncioExtras_AnuncioId" ON "AnuncioExtras" ("AnuncioId");

CREATE INDEX "IX_AnuncioExtras_ExtraId" ON "AnuncioExtras" ("ExtraId");

CREATE INDEX "IX_Anuncios_CategoriaId" ON "Anuncios" ("CategoriaId");

CREATE INDEX "IX_Anuncios_CombustivelId" ON "Anuncios" ("CombustivelId");

CREATE INDEX "IX_Anuncios_Destacado_DestaqueAte" ON "Anuncios" ("Destacado", "DestaqueAte");

CREATE INDEX "IX_Anuncios_Estado" ON "Anuncios" ("Estado");

CREATE INDEX "IX_Anuncios_MarcaId" ON "Anuncios" ("MarcaId");

CREATE INDEX "IX_Anuncios_ModeloId" ON "Anuncios" ("ModeloId");

CREATE INDEX "IX_Anuncios_TipoId" ON "Anuncios" ("TipoId");

CREATE INDEX "IX_Anuncios_VendedorId" ON "Anuncios" ("VendedorId");

CREATE INDEX "IX_AnunciosFavoritos_AnuncioId" ON "AnunciosFavoritos" ("AnuncioId");

CREATE INDEX "IX_AnunciosFavoritos_CompradorId" ON "AnunciosFavoritos" ("CompradorId");

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_Avaliacoes_CompradorId" ON "Avaliacoes" ("CompradorId");

CREATE INDEX "IX_Avaliacoes_VendedorId" ON "Avaliacoes" ("VendedorId");

CREATE INDEX "IX_Compras_AnuncioId" ON "Compras" ("AnuncioId");

CREATE INDEX "IX_Compras_CompradorId" ON "Compras" ("CompradorId");

CREATE INDEX "IX_Contactos_VendedorId" ON "Contactos" ("VendedorId");

CREATE INDEX "IX_ContactosCompradores_CompradorId" ON "ContactosCompradores" ("CompradorId");

CREATE INDEX "IX_Conversas_AnuncioId" ON "Conversas" ("AnuncioId");

CREATE INDEX "IX_Conversas_CompradorId" ON "Conversas" ("CompradorId");

CREATE INDEX "IX_Conversas_VendedorId" ON "Conversas" ("VendedorId");

CREATE INDEX "IX_Denuncia_AdministradorId" ON "Denuncia" ("AdministradorId");

CREATE INDEX "IX_Denuncia_AnuncioId" ON "Denuncia" ("AnuncioId");

CREATE INDEX "IX_Denuncia_CompradorId" ON "Denuncia" ("CompradorId");

CREATE INDEX "IX_Denuncia_UtilizadorAlvoId" ON "Denuncia" ("UtilizadorAlvoId");

CREATE INDEX "IX_Denuncia_VendedorId" ON "Denuncia" ("VendedorId");

CREATE INDEX "IX_DisponibilidadesVendedor_VendedorId" ON "DisponibilidadesVendedor" ("VendedorId");

CREATE INDEX "IX_FiltrosFavoritos_CompradorId" ON "FiltrosFavoritos" ("CompradorId");

CREATE INDEX "IX_HistoricoAcao_AdministradorId" ON "HistoricoAcao" ("AdministradorId");

CREATE INDEX "IX_HistoricoAcao_AnuncioId" ON "HistoricoAcao" ("AnuncioId");

CREATE INDEX "IX_HistoricoAcao_UtilizadorId" ON "HistoricoAcao" ("UtilizadorId");

CREATE INDEX "IX_Imagens_AnuncioId" ON "Imagens" ("AnuncioId");

CREATE UNIQUE INDEX "IX_Marcas_Nome" ON "Marcas" ("Nome");

CREATE INDEX "IX_MarcasFavoritas_CompradorId" ON "MarcasFavoritas" ("CompradorId");

CREATE INDEX "IX_MarcasFavoritas_MarcaId" ON "MarcasFavoritas" ("MarcaId");

CREATE INDEX "IX_Mensagens_ConversaId" ON "Mensagens" ("ConversaId");

CREATE INDEX "IX_Mensagens_RemetenteId" ON "Mensagens" ("RemetenteId");

CREATE INDEX "IX_Modelos_MarcaId" ON "Modelos" ("MarcaId");

CREATE UNIQUE INDEX "IX_Modelos_Nome_MarcaId" ON "Modelos" ("Nome", "MarcaId");

CREATE INDEX "IX_Modelos_TipoId" ON "Modelos" ("TipoId");

CREATE INDEX "IX_Notificacoes_AnuncioFavId" ON "Notificacoes" ("AnuncioFavId");

CREATE INDEX "IX_Notificacoes_CompradorId" ON "Notificacoes" ("CompradorId");

CREATE INDEX "IX_Notificacoes_FiltrosFavId" ON "Notificacoes" ("FiltrosFavId");

CREATE INDEX "IX_Notificacoes_MarcasFavId" ON "Notificacoes" ("MarcasFavId");

CREATE INDEX "IX_Notificacoes_PesquisasPassadasId" ON "Notificacoes" ("PesquisasPassadasId");

CREATE UNIQUE INDEX "IX_NotificationPreferences_IdentityUserId" ON "NotificationPreferences" ("IdentityUserId");

CREATE INDEX "IX_PedidosVendedor_CompradorId" ON "PedidosVendedor" ("CompradorId");

CREATE INDEX "IX_PesquisasPassadas_CompradorId" ON "PesquisasPassadas" ("CompradorId");

CREATE INDEX "IX_Reservas_AnuncioId" ON "Reservas" ("AnuncioId");

CREATE INDEX "IX_Reservas_CompradorId_Estado" ON "Reservas" ("CompradorId", "Estado");

CREATE UNIQUE INDEX "IX_Tipos_Nome" ON "Tipos" ("Nome");

CREATE INDEX "IX_Utilizador_IdentityUserId" ON "Utilizador" ("IdentityUserId");

CREATE INDEX "IX_Utilizador_MoradaId" ON "Utilizador" ("MoradaId");

CREATE INDEX "IX_Visitas_AnuncioId" ON "Visitas" ("AnuncioId");

CREATE INDEX "IX_Visitas_CompradorId" ON "Visitas" ("CompradorId");

CREATE INDEX "IX_Visitas_ReservaId" ON "Visitas" ("ReservaId");

CREATE INDEX "IX_Visitas_VendedorId" ON "Visitas" ("VendedorId");

SELECT setval(
    pg_get_serial_sequence('"Tipos"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Tipos") + 1,
        nextval(pg_get_serial_sequence('"Tipos"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260104121707_InitialCreate_Postgres', '8.0.10');

COMMIT;

